frequency: 30
delay: 3
magnetic_declination_radians: 0
yaw_offset: 1.5707963
zero_altitude: false
broadcast_utm_transform: true
publish_filtered_gps: true
use_odometry_yaw: false
wait_for_datum: false
